//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.28 at 11:25:20 PM BST 
//


package com.solace.psg.sempv1.solacesemprequest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for INTERFACE_MODE_PARAM.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="INTERFACE_MODE_PARAM"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="lacp"/&gt;
 *     &lt;enumeration value="active-backup"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "INTERFACE_MODE_PARAM")
@XmlEnum
public enum INTERFACEMODEPARAM {

    @XmlEnumValue("lacp")
    LACP("lacp"),
    @XmlEnumValue("active-backup")
    ACTIVE_BACKUP("active-backup");
    private final String value;

    INTERFACEMODEPARAM(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static INTERFACEMODEPARAM fromValue(String v) {
        for (INTERFACEMODEPARAM c: INTERFACEMODEPARAM.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
