//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.28 at 11:41:04 PM BST 
//


package com.solace.psg.sempv1.solacesempreply;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for qendpt-template--info-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="qendpt-template--info-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="message-vpn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="name-filter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="access-type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="others-permission" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="quota" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/&gt;
 *         &lt;element name="respect-message-priority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="respect-ttl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="durability-override" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="max-ttl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="dead-message-queue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="reject-msg-to-sender-on-discard" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="reject-msg-to-sender-on-discard-including-when-shutdown" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="max-delivered-unacked-msgs-per-flow" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/&gt;
 *         &lt;element name="max-redelivery" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/&gt;
 *         &lt;element name="consumer-ack-propagation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="reject-low-priority-msg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="reject-low-priority-msg-limit" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/&gt;
 *         &lt;element name="max-message-size" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/&gt;
 *         &lt;element name="max-bind-count" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="event" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="event-thresholds" type="{}event-thresholds" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "qendpt-template--info-type", propOrder = {

})
public class QendptTemplateInfoType {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "message-vpn")
    protected String messageVpn;
    @XmlElement(name = "name-filter")
    protected String nameFilter;
    protected String type;
    @XmlElement(name = "access-type")
    protected String accessType;
    @XmlElement(name = "others-permission")
    protected String othersPermission;
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger quota;
    @XmlElement(name = "respect-message-priority")
    protected String respectMessagePriority;
    @XmlElement(name = "respect-ttl")
    protected String respectTtl;
    @XmlElement(name = "durability-override")
    protected String durabilityOverride;
    @XmlElement(name = "max-ttl")
    protected String maxTtl;
    @XmlElement(name = "dead-message-queue")
    protected String deadMessageQueue;
    @XmlElement(name = "reject-msg-to-sender-on-discard")
    protected String rejectMsgToSenderOnDiscard;
    @XmlElement(name = "reject-msg-to-sender-on-discard-including-when-shutdown")
    protected String rejectMsgToSenderOnDiscardIncludingWhenShutdown;
    @XmlElement(name = "max-delivered-unacked-msgs-per-flow")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger maxDeliveredUnackedMsgsPerFlow;
    @XmlElement(name = "max-redelivery")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger maxRedelivery;
    @XmlElement(name = "consumer-ack-propagation")
    protected String consumerAckPropagation;
    @XmlElement(name = "reject-low-priority-msg")
    protected String rejectLowPriorityMsg;
    @XmlElement(name = "reject-low-priority-msg-limit")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger rejectLowPriorityMsgLimit;
    @XmlElement(name = "max-message-size")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger maxMessageSize;
    @XmlElement(name = "max-bind-count")
    @XmlSchemaType(name = "unsignedInt")
    protected Long maxBindCount;
    protected QendptTemplateInfoType.Event event;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the messageVpn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageVpn() {
        return messageVpn;
    }

    /**
     * Sets the value of the messageVpn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageVpn(String value) {
        this.messageVpn = value;
    }

    /**
     * Gets the value of the nameFilter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameFilter() {
        return nameFilter;
    }

    /**
     * Sets the value of the nameFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameFilter(String value) {
        this.nameFilter = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the accessType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessType() {
        return accessType;
    }

    /**
     * Sets the value of the accessType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessType(String value) {
        this.accessType = value;
    }

    /**
     * Gets the value of the othersPermission property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOthersPermission() {
        return othersPermission;
    }

    /**
     * Sets the value of the othersPermission property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOthersPermission(String value) {
        this.othersPermission = value;
    }

    /**
     * Gets the value of the quota property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQuota() {
        return quota;
    }

    /**
     * Sets the value of the quota property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQuota(BigInteger value) {
        this.quota = value;
    }

    /**
     * Gets the value of the respectMessagePriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespectMessagePriority() {
        return respectMessagePriority;
    }

    /**
     * Sets the value of the respectMessagePriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespectMessagePriority(String value) {
        this.respectMessagePriority = value;
    }

    /**
     * Gets the value of the respectTtl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespectTtl() {
        return respectTtl;
    }

    /**
     * Sets the value of the respectTtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespectTtl(String value) {
        this.respectTtl = value;
    }

    /**
     * Gets the value of the durabilityOverride property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDurabilityOverride() {
        return durabilityOverride;
    }

    /**
     * Sets the value of the durabilityOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDurabilityOverride(String value) {
        this.durabilityOverride = value;
    }

    /**
     * Gets the value of the maxTtl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxTtl() {
        return maxTtl;
    }

    /**
     * Sets the value of the maxTtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxTtl(String value) {
        this.maxTtl = value;
    }

    /**
     * Gets the value of the deadMessageQueue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeadMessageQueue() {
        return deadMessageQueue;
    }

    /**
     * Sets the value of the deadMessageQueue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeadMessageQueue(String value) {
        this.deadMessageQueue = value;
    }

    /**
     * Gets the value of the rejectMsgToSenderOnDiscard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRejectMsgToSenderOnDiscard() {
        return rejectMsgToSenderOnDiscard;
    }

    /**
     * Sets the value of the rejectMsgToSenderOnDiscard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRejectMsgToSenderOnDiscard(String value) {
        this.rejectMsgToSenderOnDiscard = value;
    }

    /**
     * Gets the value of the rejectMsgToSenderOnDiscardIncludingWhenShutdown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRejectMsgToSenderOnDiscardIncludingWhenShutdown() {
        return rejectMsgToSenderOnDiscardIncludingWhenShutdown;
    }

    /**
     * Sets the value of the rejectMsgToSenderOnDiscardIncludingWhenShutdown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRejectMsgToSenderOnDiscardIncludingWhenShutdown(String value) {
        this.rejectMsgToSenderOnDiscardIncludingWhenShutdown = value;
    }

    /**
     * Gets the value of the maxDeliveredUnackedMsgsPerFlow property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxDeliveredUnackedMsgsPerFlow() {
        return maxDeliveredUnackedMsgsPerFlow;
    }

    /**
     * Sets the value of the maxDeliveredUnackedMsgsPerFlow property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxDeliveredUnackedMsgsPerFlow(BigInteger value) {
        this.maxDeliveredUnackedMsgsPerFlow = value;
    }

    /**
     * Gets the value of the maxRedelivery property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxRedelivery() {
        return maxRedelivery;
    }

    /**
     * Sets the value of the maxRedelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxRedelivery(BigInteger value) {
        this.maxRedelivery = value;
    }

    /**
     * Gets the value of the consumerAckPropagation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumerAckPropagation() {
        return consumerAckPropagation;
    }

    /**
     * Sets the value of the consumerAckPropagation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumerAckPropagation(String value) {
        this.consumerAckPropagation = value;
    }

    /**
     * Gets the value of the rejectLowPriorityMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRejectLowPriorityMsg() {
        return rejectLowPriorityMsg;
    }

    /**
     * Sets the value of the rejectLowPriorityMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRejectLowPriorityMsg(String value) {
        this.rejectLowPriorityMsg = value;
    }

    /**
     * Gets the value of the rejectLowPriorityMsgLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRejectLowPriorityMsgLimit() {
        return rejectLowPriorityMsgLimit;
    }

    /**
     * Sets the value of the rejectLowPriorityMsgLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRejectLowPriorityMsgLimit(BigInteger value) {
        this.rejectLowPriorityMsgLimit = value;
    }

    /**
     * Gets the value of the maxMessageSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxMessageSize() {
        return maxMessageSize;
    }

    /**
     * Sets the value of the maxMessageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxMessageSize(BigInteger value) {
        this.maxMessageSize = value;
    }

    /**
     * Gets the value of the maxBindCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxBindCount() {
        return maxBindCount;
    }

    /**
     * Sets the value of the maxBindCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxBindCount(Long value) {
        this.maxBindCount = value;
    }

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link QendptTemplateInfoType.Event }
     *     
     */
    public QendptTemplateInfoType.Event getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link QendptTemplateInfoType.Event }
     *     
     */
    public void setEvent(QendptTemplateInfoType.Event value) {
        this.event = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="event-thresholds" type="{}event-thresholds" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "eventThresholds"
    })
    public static class Event {

        @XmlElement(name = "event-thresholds")
        protected List<EventThresholds> eventThresholds;

        /**
         * Gets the value of the eventThresholds property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the eventThresholds property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEventThresholds().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EventThresholds }
         * 
         * 
         */
        public List<EventThresholds> getEventThresholds() {
            if (eventThresholds == null) {
                eventThresholds = new ArrayList<EventThresholds>();
            }
            return this.eventThresholds;
        }

    }

}
