//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.28 at 11:41:04 PM BST 
//


package com.solace.psg.sempv1.solacesempreply;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for redundancy-info-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="redundancy-info-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="config"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;all&gt;
 *                   &lt;element name="routing-interface" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="vrrp-vrid" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                 &lt;/all&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="status"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;all&gt;
 *                   &lt;element name="activity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="vrrp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="vrrp-interfaces" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="interface" maxOccurs="unbounded" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="routing-interface" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="vrrp-priority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="detail" type="{}redundancy-detail-info-type" minOccurs="0"/&gt;
 *                 &lt;/all&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "redundancy-info-type", propOrder = {

})
public class RedundancyInfoType {

    @XmlElement(required = true)
    protected RedundancyInfoType.Config config;
    @XmlElement(required = true)
    protected RedundancyInfoType.Status status;

    /**
     * Gets the value of the config property.
     * 
     * @return
     *     possible object is
     *     {@link RedundancyInfoType.Config }
     *     
     */
    public RedundancyInfoType.Config getConfig() {
        return config;
    }

    /**
     * Sets the value of the config property.
     * 
     * @param value
     *     allowed object is
     *     {@link RedundancyInfoType.Config }
     *     
     */
    public void setConfig(RedundancyInfoType.Config value) {
        this.config = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link RedundancyInfoType.Status }
     *     
     */
    public RedundancyInfoType.Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link RedundancyInfoType.Status }
     *     
     */
    public void setStatus(RedundancyInfoType.Status value) {
        this.status = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;all&gt;
     *         &lt;element name="routing-interface" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="vrrp-vrid" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *       &lt;/all&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Config {

        @XmlElement(name = "routing-interface", required = true)
        protected String routingInterface;
        @XmlElement(name = "vrrp-vrid")
        protected int vrrpVrid;

        /**
         * Gets the value of the routingInterface property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRoutingInterface() {
            return routingInterface;
        }

        /**
         * Sets the value of the routingInterface property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRoutingInterface(String value) {
            this.routingInterface = value;
        }

        /**
         * Gets the value of the vrrpVrid property.
         * 
         */
        public int getVrrpVrid() {
            return vrrpVrid;
        }

        /**
         * Sets the value of the vrrpVrid property.
         * 
         */
        public void setVrrpVrid(int value) {
            this.vrrpVrid = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;all&gt;
     *         &lt;element name="activity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="vrrp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="vrrp-interfaces" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="interface" maxOccurs="unbounded" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="routing-interface" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="vrrp-priority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="detail" type="{}redundancy-detail-info-type" minOccurs="0"/&gt;
     *       &lt;/all&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Status {

        @XmlElement(required = true)
        protected String activity;
        protected String vrrp;
        @XmlElement(name = "vrrp-interfaces")
        protected RedundancyInfoType.Status.VrrpInterfaces vrrpInterfaces;
        @XmlElement(name = "routing-interface")
        protected String routingInterface;
        @XmlElement(name = "vrrp-priority")
        protected String vrrpPriority;
        protected RedundancyDetailInfoType detail;

        /**
         * Gets the value of the activity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActivity() {
            return activity;
        }

        /**
         * Sets the value of the activity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActivity(String value) {
            this.activity = value;
        }

        /**
         * Gets the value of the vrrp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVrrp() {
            return vrrp;
        }

        /**
         * Sets the value of the vrrp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVrrp(String value) {
            this.vrrp = value;
        }

        /**
         * Gets the value of the vrrpInterfaces property.
         * 
         * @return
         *     possible object is
         *     {@link RedundancyInfoType.Status.VrrpInterfaces }
         *     
         */
        public RedundancyInfoType.Status.VrrpInterfaces getVrrpInterfaces() {
            return vrrpInterfaces;
        }

        /**
         * Sets the value of the vrrpInterfaces property.
         * 
         * @param value
         *     allowed object is
         *     {@link RedundancyInfoType.Status.VrrpInterfaces }
         *     
         */
        public void setVrrpInterfaces(RedundancyInfoType.Status.VrrpInterfaces value) {
            this.vrrpInterfaces = value;
        }

        /**
         * Gets the value of the routingInterface property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRoutingInterface() {
            return routingInterface;
        }

        /**
         * Sets the value of the routingInterface property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRoutingInterface(String value) {
            this.routingInterface = value;
        }

        /**
         * Gets the value of the vrrpPriority property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVrrpPriority() {
            return vrrpPriority;
        }

        /**
         * Sets the value of the vrrpPriority property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVrrpPriority(String value) {
            this.vrrpPriority = value;
        }

        /**
         * Gets the value of the detail property.
         * 
         * @return
         *     possible object is
         *     {@link RedundancyDetailInfoType }
         *     
         */
        public RedundancyDetailInfoType getDetail() {
            return detail;
        }

        /**
         * Sets the value of the detail property.
         * 
         * @param value
         *     allowed object is
         *     {@link RedundancyDetailInfoType }
         *     
         */
        public void setDetail(RedundancyDetailInfoType value) {
            this.detail = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="interface" maxOccurs="unbounded" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "_interface"
        })
        public static class VrrpInterfaces {

            @XmlElement(name = "interface")
            protected List<RedundancyInfoType.Status.VrrpInterfaces.Interface> _interface;

            /**
             * Gets the value of the interface property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the interface property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getInterface().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link RedundancyInfoType.Status.VrrpInterfaces.Interface }
             * 
             * 
             */
            public List<RedundancyInfoType.Status.VrrpInterfaces.Interface> getInterface() {
                if (_interface == null) {
                    _interface = new ArrayList<RedundancyInfoType.Status.VrrpInterfaces.Interface>();
                }
                return this._interface;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "name",
                "status"
            })
            public static class Interface {

                @XmlElement(required = true)
                protected String name;
                @XmlElement(required = true)
                protected String status;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the status property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStatus() {
                    return status;
                }

                /**
                 * Sets the value of the status property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStatus(String value) {
                    this.status = value;
                }

            }

        }

    }

}
