//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.28 at 11:41:04 PM BST 
//


package com.solace.psg.sempv1.solacesempreply;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for redundancy-mismatch-info-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="redundancy-mismatch-info-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="primary-cvrid" type="{}ip-address-only"/&gt;
 *         &lt;element name="backup-cvrid" type="{}ip-address-only"/&gt;
 *         &lt;element name="mate-address" type="{}ip-address-only"/&gt;
 *         &lt;element name="ad-enabled-cvrid" type="{}ip-address-only"/&gt;
 *         &lt;element name="disk-wwn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="primary-vrrp" type="{}redundancy-vrrp-interface-mismatch-info-type"/&gt;
 *         &lt;element name="backup-vrrp" type="{}redundancy-vrrp-interface-mismatch-info-type"/&gt;
 *         &lt;element name="ad-enabled-vrrp" type="{}redundancy-vrrp-interface-mismatch-info-type"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "redundancy-mismatch-info-type", propOrder = {
    "primaryCvrid",
    "backupCvrid",
    "mateAddress",
    "adEnabledCvrid",
    "diskWwn",
    "primaryVrrp",
    "backupVrrp",
    "adEnabledVrrp"
})
public class RedundancyMismatchInfoType {

    @XmlElement(name = "primary-cvrid", required = true)
    protected IpAddressOnly primaryCvrid;
    @XmlElement(name = "backup-cvrid", required = true)
    protected IpAddressOnly backupCvrid;
    @XmlElement(name = "mate-address", required = true)
    protected IpAddressOnly mateAddress;
    @XmlElement(name = "ad-enabled-cvrid", required = true)
    protected IpAddressOnly adEnabledCvrid;
    @XmlElement(name = "disk-wwn", required = true)
    protected String diskWwn;
    @XmlElement(name = "primary-vrrp", required = true)
    protected RedundancyVrrpInterfaceMismatchInfoType primaryVrrp;
    @XmlElement(name = "backup-vrrp", required = true)
    protected RedundancyVrrpInterfaceMismatchInfoType backupVrrp;
    @XmlElement(name = "ad-enabled-vrrp", required = true)
    protected RedundancyVrrpInterfaceMismatchInfoType adEnabledVrrp;

    /**
     * Gets the value of the primaryCvrid property.
     * 
     * @return
     *     possible object is
     *     {@link IpAddressOnly }
     *     
     */
    public IpAddressOnly getPrimaryCvrid() {
        return primaryCvrid;
    }

    /**
     * Sets the value of the primaryCvrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link IpAddressOnly }
     *     
     */
    public void setPrimaryCvrid(IpAddressOnly value) {
        this.primaryCvrid = value;
    }

    /**
     * Gets the value of the backupCvrid property.
     * 
     * @return
     *     possible object is
     *     {@link IpAddressOnly }
     *     
     */
    public IpAddressOnly getBackupCvrid() {
        return backupCvrid;
    }

    /**
     * Sets the value of the backupCvrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link IpAddressOnly }
     *     
     */
    public void setBackupCvrid(IpAddressOnly value) {
        this.backupCvrid = value;
    }

    /**
     * Gets the value of the mateAddress property.
     * 
     * @return
     *     possible object is
     *     {@link IpAddressOnly }
     *     
     */
    public IpAddressOnly getMateAddress() {
        return mateAddress;
    }

    /**
     * Sets the value of the mateAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link IpAddressOnly }
     *     
     */
    public void setMateAddress(IpAddressOnly value) {
        this.mateAddress = value;
    }

    /**
     * Gets the value of the adEnabledCvrid property.
     * 
     * @return
     *     possible object is
     *     {@link IpAddressOnly }
     *     
     */
    public IpAddressOnly getAdEnabledCvrid() {
        return adEnabledCvrid;
    }

    /**
     * Sets the value of the adEnabledCvrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link IpAddressOnly }
     *     
     */
    public void setAdEnabledCvrid(IpAddressOnly value) {
        this.adEnabledCvrid = value;
    }

    /**
     * Gets the value of the diskWwn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiskWwn() {
        return diskWwn;
    }

    /**
     * Sets the value of the diskWwn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiskWwn(String value) {
        this.diskWwn = value;
    }

    /**
     * Gets the value of the primaryVrrp property.
     * 
     * @return
     *     possible object is
     *     {@link RedundancyVrrpInterfaceMismatchInfoType }
     *     
     */
    public RedundancyVrrpInterfaceMismatchInfoType getPrimaryVrrp() {
        return primaryVrrp;
    }

    /**
     * Sets the value of the primaryVrrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link RedundancyVrrpInterfaceMismatchInfoType }
     *     
     */
    public void setPrimaryVrrp(RedundancyVrrpInterfaceMismatchInfoType value) {
        this.primaryVrrp = value;
    }

    /**
     * Gets the value of the backupVrrp property.
     * 
     * @return
     *     possible object is
     *     {@link RedundancyVrrpInterfaceMismatchInfoType }
     *     
     */
    public RedundancyVrrpInterfaceMismatchInfoType getBackupVrrp() {
        return backupVrrp;
    }

    /**
     * Sets the value of the backupVrrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link RedundancyVrrpInterfaceMismatchInfoType }
     *     
     */
    public void setBackupVrrp(RedundancyVrrpInterfaceMismatchInfoType value) {
        this.backupVrrp = value;
    }

    /**
     * Gets the value of the adEnabledVrrp property.
     * 
     * @return
     *     possible object is
     *     {@link RedundancyVrrpInterfaceMismatchInfoType }
     *     
     */
    public RedundancyVrrpInterfaceMismatchInfoType getAdEnabledVrrp() {
        return adEnabledVrrp;
    }

    /**
     * Sets the value of the adEnabledVrrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link RedundancyVrrpInterfaceMismatchInfoType }
     *     
     */
    public void setAdEnabledVrrp(RedundancyVrrpInterfaceMismatchInfoType value) {
        this.adEnabledVrrp = value;
    }

}
