//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb"&gt;http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 09:27:13 AM GMT 
//


package com.solace.psg.sempv1.solacesempreply;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for virtual-router-index.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="virtual-router-index"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="primary"/&gt;
 *     &lt;enumeration value="backup"/&gt;
 *     &lt;enumeration value="internal"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "virtual-router-index")
@XmlEnum
public enum VirtualRouterIndex {

    @XmlEnumValue("primary")
    PRIMARY("primary"),
    @XmlEnumValue("backup")
    BACKUP("backup"),
    @XmlEnumValue("internal")
    INTERNAL("internal");
    private final String value;

    VirtualRouterIndex(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VirtualRouterIndex fromValue(String v) {
        for (VirtualRouterIndex c : VirtualRouterIndex.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
